urban_project/board/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'board'

urlpatterns = [
    path('', views.advertisement_list, name='advertisement_list'),
    path('advertisement/<int:pk>/', views.advertisement_detail, name='advertisement_detail'),
    path('advertisements/<int:pk>/like/', views.like_ad, name='like_ad'),
    path('advertisements/<int:pk>/dislike/', views.dislike_ad, name='dislike_ad'),
    path('add/', views.add_advertisement, name='add_advertisement'),
    path('edit/<int:pk>', views.edit_advertisement, name='edit_advertisement'),
    path('delete/<int:pk>', views.delete_advertisement, name='delete_advertisement'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urban_project/urban_project/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views as board_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('accounts/logout/', board_views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', board_views.home, name='home'),
    path('signup/', board_views.signup, name='signup'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urban_project/board/models.py
from django.db import models
from django.contrib.auth.models import User


class Advertisement(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="photos/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    def __str__(self):
        return self.title


class Comment(models.Model):
    advertisement = models.ForeignKey(Advertisement, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.advertisement}'

urban_project/board/forms.py
from django import forms
from .models import Advertisement
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ['title', 'content', 'author', 'image']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

urban_project/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from board.models import Advertisement
from board.forms import AdvertisementForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator

def logout_view(request):
    '''
    Представление для выхода из систему пользователя
    :param request: запроос
    :return: Возвращает домашнюю страницу
    '''
    logout(request)
    return redirect('home')


from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import login, authenticate


def signup(request):
    '''
    Представление для регистрации в системе пользователя
    :param request: запрос
    :return: регистрирует пользователя в системе
    '''
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/board')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def home(request):
    '''
    Домашняя страница
    :param request: запрос
    :return: возвращает домашнюю страницу
    '''
    return render(request, 'home.html')


def advertisement_list(request):
    '''
    Представление для вывода всех объявлений
    :param request: запрос
    :return: Возвращает страницу с всеми объявлениями
    '''
    advertisements = Advertisement.objects.all()
    return render(request, 'board/advertisement_list.html', {'advertisements': advertisements})


def advertisement_detail(request, pk):
    '''
    Выводит конкретное объявление через id
    :param request: запрос
    :param pk: if
    :return: страницу с id объявлением
    '''
    advertisement = Advertisement.objects.get(pk=pk)
    return render(request, 'board/advertisement_detail.html', {'advertisement': advertisement})


@login_required
def edit_advertisement(request, pk):
    '''
    Представление для редактирования объявлений
    :param request: запрос
    :param pk: id объявления
    :return: Редактирует объявления и возращает страницу объявлений
    '''
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)
        if form.is_valid():
            advertisement.save()
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm(instance=advertisement)
    return render(request, 'board/edit_advertisement.html', {'form': form, 'advertisement': advertisement})


@login_required
def add_advertisement(request):
    '''
    Представление для добавления объявления
    :param request: запрос
    :return: Добавляет объявление и выводит список представлений
    '''
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.author = request.user
            advertisement.save()
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementForm()
    return render(request, 'board/add_advertisement.html', {'form': form})


@login_required
def delete_advertisement(request, pk):
    '''
    Представление для удаления объявления
    :param request: запрос
    :param pk: id  объявления
    :return: Удаляет объявление и возвращает на страницу объявлений
    '''
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        advertisement.delete()
        messages.success(request, 'Объявление успешно удалено.')
        return redirect('board:advertisement_list')
    return render(request, 'board/delete_advertisement.html', {'advertisement': advertisement})


@login_required
def like_ad(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        advertisement.likes += 1
        advertisement.save()
        return redirect('board:advertisement_detail', pk=advertisement.pk)


@login_required
def dislike_ad(request, pk):
    advertisement = Advertisement.objects.get(pk=pk)
    if request.method == "POST":
        advertisement.dislikes += 1
        advertisement.save()
        return redirect('board:advertisement_detail', pk=advertisement.pk)

def advertisement_list(request):
    '''
    Представление для вывода всех объявлений с пагинацией
    :param request: запрос
    :return: Возвращает страницу с всеми объявлениями
    '''
    advertisements = Advertisement.objects.all()
    paginator = Paginator(advertisements, 3)  # Показывать 10 объявлений на странице

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'board/advertisement_list.html', {'page_obj': page_obj})

urban_project/board/templates/board/add_advertisement.html
{% extends 'base.html' %}

{% block content %}
<h2>Add Advertisement</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

urban_project/board/templates/board/advertisement_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ advertisement.title }}</h1>
<p>{{ advertisement.content }}</p>
{% if advertisement.image %}
<p><img class="img-article-left" src="{{advertisement.image.url}}"</p>
{% endif %}
<p></p>
<p> Автор объявления :<h2> {{advertisement.author}}</h2></p>
<p></p>
<p>Лайки: {{ advertisement.likes }} | Дизлайки: {{ advertisement.dislikes }}</p>

{% if user.is_authenticated %}
<form action="{% url 'board:like_ad' advertisement.pk %}" method="post">
    {% csrf_token %}
    <button type="submit">Like</button>
</form>

<form action="{% url 'board:dislike_ad' advertisement.pk %}" method="post">
    {% csrf_token %}
    <button type="submit">Dislike</button>
</form>

<a href="{% url 'board:advertisement_list' %}">  <button>Вернуться обратно к представлениям</button></a>
<p> </p>
<a href="{% url 'board:edit_advertisement' pk=advertisement.pk %}">
    <button>Edit Advertisement</button>
</a>
<a href="{% url 'board:delete_advertisement' pk=advertisement.pk %}">
    <button>Delete Advertisement</button>
</a>
{% endif %}


{% endblock %}

urban_project/board/templates/board/advertisement_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Advertisements</h1>
{% if user.is_authenticated %}
<a href="{% url 'board:add_advertisement' %}">
    <button>Add Advertisement</button>
</a>

{% endif %}
<ul>
    {% for advertisement in page_obj %}
        <li>
            <a href="{% url 'board:advertisement_detail' advertisement.pk %}">{{ advertisement.title }}</a>
        </li>
    {% empty %}
        <li>Нет объявлений.</li>
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

urban_project/board/templates/board/delete_advertisement.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<h2> Delete Adversement</h2>
<body>
<h1>Подтвердите удаление объявления</h1>
<p>Вы уверены, что хотите удалить объявление "
<h1>{{ advertisement.title }}?</h1>
</p>
{% if advertisement.image %}
<p><img class="img-article-left" src="{{advertisement.image.url}}"</p>
{% endif %}
<p></p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <button><a href="{% url 'board:advertisement_list' %}">Отмена</a></button>

</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li
            {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
</body>
{% endif %}
{% endblock %}

urban_project/board/templates/board/edit_advertisement.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<h2> Editing Adversement</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endif %}
{% endblock %}

urban_project/board/templates/signup.html
<!-- your_app/templates/signup.html -->
{% extends 'base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

urban_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Django Project{% endblock %}</title>
    <style>
        .navbar {
            overflow: hidden;
            background-color: #333;
            padding: 14px 16px;
        }
        .navbar a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 12px;
            text-decoration: none;
            font-size: 17px;
        }
        .navbar a:hover {
            background-color: #ddd;
            color: black;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'board:advertisement_list' %}">Board</a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}

</body>
</html>

urban_project/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Welcome to Our Site!</h1>
    <p><a href="/board/">Go to the board</a></p>
</body>
</html>